"use client";

import { useMemo, useState } from "react";
import { inspirationExperiences, recommendCities, travelRanges, type InspirationPriority, type TravelRange } from "./destination-recommendations";

export function DestinationRecommender({ days, departureCity, onDepartureCity, onChoose }: { days: number; departureCity: string; onDepartureCity: (value: string) => void; onChoose: (city: string) => void }) {
  const [open,setOpen] = useState(false); const [priorities,setPriorities] = useState<InspirationPriority[]>([]); const [range,setRange] = useState<TravelRange>("rail");
  const results = useMemo(() => recommendCities(priorities, range, days, departureCity), [priorities,range,days,departureCity]);
  return <div className="mt-4"><button type="button" onClick={() => setOpen((value) => !value)} className="text-sm font-bold text-[#245b46] underline decoration-[#245b46]/25 underline-offset-4">还没想好去哪？帮我选一个</button>{open && <div className="mt-4 rounded-2xl border border-[#245b46]/12 bg-[#f4f7f2] p-4 sm:p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">从哪里出发（选填）<input value={departureCity} onChange={(event) => onDepartureCity(event.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-2.5" placeholder="例如：长沙" /></label><div><p className="text-sm font-semibold">可接受交通范围</p><div className="mt-2 flex flex-wrap gap-2">{travelRanges.map((item) => <button type="button" key={item.value} onClick={() => setRange(item.value)} className={`rounded-full border px-3 py-2 text-xs font-bold ${range === item.value ? "border-[#245b46] bg-[#e3eee7]" : "border-black/10 bg-white"}`}>{item.label}</button>)}</div></div></div><div className="mt-4"><p className="text-sm font-semibold">最在意的体验 <span className="font-normal text-[#707a74]">最多2项</span></p><div className="mt-2 flex flex-wrap gap-2">{inspirationExperiences.map((item) => <button type="button" key={item.value} onClick={() => setPriorities((current) => current.includes(item.value) ? current.filter((value) => value !== item.value) : current.length < 2 ? [...current,item.value] : current)} className={`rounded-full border px-3 py-2 text-xs font-bold ${priorities.includes(item.value) ? "border-[#245b46] bg-[#e3eee7]" : "border-black/10 bg-white"}`}>{item.label}</button>)}</div></div>{!results.precise && range !== "domestic" && <p className="mt-4 rounded-xl bg-[#fff7e9] px-3 py-2 text-xs leading-5 text-[#785f41]">暂未覆盖该出发地的可靠周边关系，当前按旅行偏好为你提供灵感。</p>}<div className="mt-5 grid gap-3 sm:grid-cols-3">{results.items.map((item) => <article key={item.city} className="rounded-2xl bg-white p-4 shadow-sm"><h3 className="text-lg font-bold">{item.city}</h3><p className="mt-2 text-xs leading-5 text-[#65706a]">{item.reason}</p><p className="mt-3 text-xs font-semibold text-[#245b46]">{item.days} · {item.play}</p><button type="button" onClick={() => { onChoose(item.city); setOpen(false); }} className="mt-4 w-full rounded-full bg-[#245b46] px-3 py-2 text-sm font-bold text-white">就去这里</button></article>)}</div><p className="mt-3 text-xs text-[#7b847e]">推荐基于静态城市规则，不包含实时车次、票价和天气。</p></div>}</div>;
}
