import { NextResponse } from "next/server";
import { desc, eq, gte } from "drizzle-orm";
import { hasAdminAccess } from "@/server/auth/admin";
import { ensureAnalyticsTable } from "@/server/database/analytics";
import { getDatabase } from "@/server/database/client";
import { analyticsEvents, generationJobs, trips } from "@/server/database/schema";
import { startOfShanghaiDay } from "@/server/database/trips";
import { getImageAdminMetrics } from "@/server/database/trip-images";

const failureLabel: Record<string, string> = { INVALID_TRIP_INPUT:"客户端校验失败",GENERATION_IN_PROGRESS:"重复请求",OPENAI_AUTH_ERROR:"AI服务认证异常",OPENAI_QUOTA_ERROR:"AI服务限流",OPENAI_TIMEOUT:"AI服务超时",JSON_PARSE_FAILED:"输出格式不完整",INVALID_SCHEMA:"结构校验失败",TIME_OVERLAP:"活动时间冲突",TRANSPORT_GAP:"交通时间不足",DUPLICATE_ACTIVITY:"活动地点重复",FUZZY_PLACE:"地点不够明确",MAIN_ACTIVITY_LIMIT:"活动数量过多",WALKING_LIMIT:"步行强度过高",BUDGET_LIMIT:"超过用户预算",BUDGET_RECONCILIATION:"费用加总不一致",PROVINCE_TRIP_NOT_EXPANDED:"省内多地未展开",TOO_MANY_CITIES:"落脚点过多",UNREALISTIC_TRANSFER:"跨城交通不合理",QUALITY_VALIDATION_FAILED:"其他质量检查未通过",VALIDATION_FAILED:"其他质量检查未通过",DATABASE_ERROR:"数据库异常",FUNCTION_TIMEOUT:"服务器超时",UNKNOWN_ERROR:"未知错误" };
const percentile = (values: number[], ratio: number) => values.length ? [...values].sort((a, b) => a - b)[Math.min(values.length - 1, Math.floor(values.length * ratio))] : 0;

export async function GET() {
  if (!await hasAdminAccess()) return NextResponse.json({ error: "未授权" }, { status: 401 });
  await ensureAnalyticsTable(); const now = Date.now(); const since = new Date(now - 30 * 86_400_000); const db = getDatabase();
  const jobs = await db.select({ id: generationJobs.id, type: generationJobs.type, status: generationJobs.status, duration: generationJobs.durationMs, error: generationJobs.errorCode, createdAt: generationJobs.createdAt, tripId: generationJobs.tripId, input: trips.inputJson }).from(generationJobs).leftJoin(trips, eq(generationJobs.tripId, trips.id)).where(gte(generationJobs.createdAt, since)).orderBy(desc(generationJobs.createdAt)).limit(1000);
  const events = await db.select().from(analyticsEvents).where(gte(analyticsEvents.createdAt, since)).orderBy(desc(analyticsEvents.createdAt)).limit(5000);
  const full = jobs.filter((job) => job.type === "full_generation"); const completed = full.filter((job) => job.status === "completed"); const failed = full.filter((job) => job.status === "failed"); const durations = completed.map((job) => job.duration || 0).filter(Boolean); const revisions = jobs.filter((job) => job.type === "day_revision"); const revisionSuccess = revisions.filter((job) => job.status === "completed");
  const count = (name: string) => events.filter((event) => event.eventName === name).length; const uniqueEventVisitors=(names:string[])=>new Set(events.filter(event=>names.includes(event.eventName)).map(event=>event.visitorId)).size; const visitors = new Set(events.map((event) => event.visitorId)).size; const homeViews = events.filter((event) => event.eventName === "page_view" && event.pageName === "home").length; const homeDurations = events.filter((event) => event.eventName === "page_duration" && event.pageName === "home").map((event) => event.durationMs || 0).filter(Boolean); const generateClicks = count("generate_clicked");
  const failures = Object.entries(failed.reduce<Record<string, number>>((result, job) => ({ ...result, [job.error || "UNKNOWN_ERROR"]: (result[job.error || "UNKNOWN_ERROR"] || 0) + 1 }), {})).map(([code, value]) => ({ code, label: failureLabel[code] || "其他错误", value, ratio: failed.length ? value / failed.length : 0 }));
  const todayStart=startOfShanghaiDay();
  const imageMetrics=await getImageAdminMetrics(todayStart);
  Object.assign(imageMetrics,{posterExampleVisitors:uniqueEventVisitors(["poster_example_open_top","poster_example_open_bottom"]),posterGenerateClickVisitors:uniqueEventVisitors(["poster_generate_click_top","poster_generate_click_bottom"]),posterLoginPrompts:count("poster_login_prompt_shown"),posterStarted:count("poster_generation_started"),posterSucceeded:count("poster_generation_succeeded")+count("travel_poster_succeeded"),posterFailed:count("poster_generation_failed"),posterSaveCurrent:count("poster_save_current"),posterSaveAll:count("poster_save_all"),posterShares:count("poster_share")});
  const usage=events.filter(event=>event.eventName==="ai_usage"&&new Date(event.createdAt)>=todayStart);const usageNumber=(event:typeof usage[number],key:string)=>Number(event.metadata?.[key]||0);const totalCost=usage.reduce((sum,event)=>sum+usageNumber(event,"estimatedCostUsd"),0);const costFor=(name:string)=>usage.filter(event=>String(event.metadata?.requestType||"").includes(name)).reduce((sum,event)=>sum+usageNumber(event,"estimatedCostUsd"),0);
  const styles = Object.entries(full.reduce<Record<string, number>>((result, job) => job.input ? ({ ...result, [job.input.travelStyle]: (result[job.input.travelStyle] || 0) + 1 }) : result, {})); const interests = Object.entries(full.flatMap((job) => job.input?.priorities || []).reduce<Record<string, number>>((result, value) => ({ ...result, [value]: (result[value] || 0) + 1 }), {})); const devices = Object.entries(events.filter((event) => event.eventName === "page_view").reduce<Record<string, number>>((result, event) => { const value = String(event.metadata?.device || "unknown"); return { ...result, [value]: (result[value] || 0) + 1 }; }, {}));
  const styleStats=styles.map(([style,total])=>{const subset=full.filter(job=>job.input?.travelStyle===style);const success=subset.filter(job=>job.status==="completed").length;const revisionsForStyle=revisions.filter(job=>job.input?.travelStyle===style).length;const styleDurations=subset.map(job=>job.duration||0).filter(Boolean);return{style,total,successRate:total?success/total:0,failureRate:total?(total-success)/total:0,revisionRate:total?revisionsForStyle/total:0,averageDurationMs:styleDurations.length?Math.round(styleDurations.reduce((a,b)=>a+b,0)/styleDurations.length):0}});
  const trend = [1, 7, 30].map((days) => { const subset = full.filter((job) => new Date(job.createdAt).getTime() >= now - days * 86_400_000); const success = subset.filter((job) => job.status === "completed").length; return { days, total: subset.length, success, successRate: subset.length ? success / subset.length : 0 }; });
  return NextResponse.json({ metrics: { pageViews: count("page_view"), visitors, averageHomeDurationMs: homeDurations.length ? Math.round(homeDurations.reduce((a, b) => a + b, 0) / homeDurations.length) : 0, generateClicks, conversionRate: homeViews ? generateClicks / homeViews : 0, generated: full.length, success: completed.length, failed: failed.length, successRate: full.length ? completed.length / full.length : 0, failureRate: full.length ? failed.length / full.length : 0, averageDurationMs: durations.length ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : 0, p50Ms: percentile(durations, .5), p90Ms: percentile(durations, .9), revisions: revisions.length, revisionSuccessRate: revisions.length ? revisionSuccess.length / revisions.length : 0, shares: count("share_clicked"), images: count("day_image_saved"), feedback: count("feedback_submitted"),todayAiRequests:usage.length,todayAiCostUsd:totalCost,fullGenerationCostUsd:costFor("trip_plan"),dayRevisionCostUsd:costFor("day_revision"),partialRevisionCostUsd:costFor("partial_revision"),repairCostUsd:usage.filter(event=>event.metadata?.repairAttempt===true).reduce((sum,event)=>sum+usageNumber(event,"estimatedCostUsd"),0),rateLimited:count("ai_rate_limited"),idempotentReused:count("idempotent_reused"),premiumImageTasks:imageMetrics.total,premiumImageSuccess:imageMetrics.succeeded,premiumImageFailed:imageMetrics.failed,premiumImageAverageDurationMs:imageMetrics.averageDurationMs,premiumImageCostUsd:imageMetrics.totalCostUsd,premiumImageFreeCreditsUsed:imageMetrics.freeCreditsUsed,premiumImageSaved:count("travel_poster_saved"),premiumImageShared:count("travel_poster_shared") }, imageMetrics, failures, styles, styleStats, interests, devices, trend, records: full.slice(0, 100).map((job) => ({ id: job.id, createdAt: job.createdAt, tripId: job.tripId, destination: job.input?.destination.city || "—", days: job.input?.days || 0, style: job.input?.travelStyle || "—", companion: job.input?.companionType || "—", status: job.status, duration: job.duration, error: job.error ? failureLabel[job.error] || "其他错误" : null })) });
}
