import { NextResponse } from "next/server";
import { desc, eq, gte } from "drizzle-orm";
import { hasAdminAccess } from "@/server/auth/admin";
import { ensureAnalyticsTable } from "@/server/database/analytics";
import { getDatabase } from "@/server/database/client";
import { analyticsEvents, generationJobs, trips } from "@/server/database/schema";

const failureLabel: Record<string, string> = { INVALID_TRIP_INPUT: "客户端校验失败", GENERATION_IN_PROGRESS: "重复请求", OPENAI_AUTH_ERROR: "AI服务认证异常", OPENAI_QUOTA_ERROR: "AI服务限流", OPENAI_TIMEOUT: "AI服务超时", JSON_PARSE_FAILED: "输出格式不完整", SCHEMA_VALIDATION_FAILED: "结构校验失败", QUALITY_VALIDATION_FAILED: "行程质量检查未通过", VALIDATION_FAILED: "行程质量检查未通过", DATABASE_ERROR: "数据库异常", FUNCTION_TIMEOUT: "服务器超时", UNKNOWN_ERROR: "未知错误" };
const percentile = (values: number[], ratio: number) => values.length ? [...values].sort((a, b) => a - b)[Math.min(values.length - 1, Math.floor(values.length * ratio))] : 0;

export async function GET() {
  if (!await hasAdminAccess()) return NextResponse.json({ error: "未授权" }, { status: 401 });
  await ensureAnalyticsTable(); const now = Date.now(); const since = new Date(now - 30 * 86_400_000); const db = getDatabase();
  const jobs = await db.select({ id: generationJobs.id, type: generationJobs.type, status: generationJobs.status, duration: generationJobs.durationMs, error: generationJobs.errorCode, createdAt: generationJobs.createdAt, tripId: generationJobs.tripId, input: trips.inputJson }).from(generationJobs).leftJoin(trips, eq(generationJobs.tripId, trips.id)).where(gte(generationJobs.createdAt, since)).orderBy(desc(generationJobs.createdAt)).limit(1000);
  const events = await db.select().from(analyticsEvents).where(gte(analyticsEvents.createdAt, since)).orderBy(desc(analyticsEvents.createdAt)).limit(5000);
  const full = jobs.filter((job) => job.type === "full_generation"); const completed = full.filter((job) => job.status === "completed"); const failed = full.filter((job) => job.status === "failed"); const durations = completed.map((job) => job.duration || 0).filter(Boolean); const revisions = jobs.filter((job) => job.type === "day_revision"); const revisionSuccess = revisions.filter((job) => job.status === "completed");
  const count = (name: string) => events.filter((event) => event.eventName === name).length; const visitors = new Set(events.map((event) => event.visitorId)).size; const homeViews = events.filter((event) => event.eventName === "page_view" && event.pageName === "home").length; const homeDurations = events.filter((event) => event.eventName === "page_duration" && event.pageName === "home").map((event) => event.durationMs || 0).filter(Boolean); const generateClicks = count("generate_clicked");
  const failures = Object.entries(failed.reduce<Record<string, number>>((result, job) => ({ ...result, [job.error || "UNKNOWN_ERROR"]: (result[job.error || "UNKNOWN_ERROR"] || 0) + 1 }), {})).map(([code, value]) => ({ code, label: failureLabel[code] || "其他错误", value, ratio: failed.length ? value / failed.length : 0 }));
  const styles = Object.entries(full.reduce<Record<string, number>>((result, job) => job.input ? ({ ...result, [job.input.travelStyle]: (result[job.input.travelStyle] || 0) + 1 }) : result, {})); const interests = Object.entries(full.flatMap((job) => job.input?.priorities || []).reduce<Record<string, number>>((result, value) => ({ ...result, [value]: (result[value] || 0) + 1 }), {})); const devices = Object.entries(events.filter((event) => event.eventName === "page_view").reduce<Record<string, number>>((result, event) => { const value = String(event.metadata?.device || "unknown"); return { ...result, [value]: (result[value] || 0) + 1 }; }, {}));
  const trend = [1, 7, 30].map((days) => { const subset = full.filter((job) => new Date(job.createdAt).getTime() >= now - days * 86_400_000); const success = subset.filter((job) => job.status === "completed").length; return { days, total: subset.length, success, successRate: subset.length ? success / subset.length : 0 }; });
  return NextResponse.json({ metrics: { pageViews: count("page_view"), visitors, averageHomeDurationMs: homeDurations.length ? Math.round(homeDurations.reduce((a, b) => a + b, 0) / homeDurations.length) : 0, generateClicks, conversionRate: homeViews ? generateClicks / homeViews : 0, generated: full.length, success: completed.length, failed: failed.length, successRate: full.length ? completed.length / full.length : 0, failureRate: full.length ? failed.length / full.length : 0, averageDurationMs: durations.length ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : 0, p50Ms: percentile(durations, .5), p90Ms: percentile(durations, .9), revisions: revisions.length, revisionSuccessRate: revisions.length ? revisionSuccess.length / revisions.length : 0, shares: count("share_clicked"), images: count("day_image_saved"), feedback: count("feedback_submitted") }, failures, styles, interests, devices, trend, records: full.slice(0, 100).map((job) => ({ id: job.id, createdAt: job.createdAt, tripId: job.tripId, destination: job.input?.destination.city || "—", days: job.input?.days || 0, style: job.input?.travelStyle || "—", companion: job.input?.companionType || "—", status: job.status, duration: job.duration, error: job.error ? failureLabel[job.error] || "其他错误" : null })) });
}
