"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {trackEvent} from "@/features/analytics/client";
type Summary={emailMasked:string;points:{available:number;reserved:number;lifetimeGranted:number;lifetimeConsumed:number};tripCount:number;posterCount:number};
type Trip={id:string;destination:string;days:number;title:string;status:string;updatedAt:string;poster:{status:string;pages:number}};
type Point={id:string;label:string;amount:number;balanceAfter:number;createdAt:string};
type Tab="trips"|"points"|"settings";
export function AccountClient({contactEmail}:{contactEmail:string|null}){const[tab,setTab]=useState<Tab>("trips"),[summary,setSummary]=useState<Summary|null>(null),[trips,setTrips]=useState<Trip[]>([]),[points,setPoints]=useState<Point[]>([]),[tripPage,setTripPage]=useState(1),[pointPage,setPointPage]=useState(1),[tripMore,setTripMore]=useState(false),[pointMore,setPointMore]=useState(false),[message,setMessage]=useState("");
  const loadSummary=useCallback(()=>fetch("/api/account/summary",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setSummary),[]);
  useEffect(()=>{void loadSummary();},[loadSummary]);
  useEffect(()=>{if(tab!=="trips")return;fetch(`/api/account/trips?page=${tripPage}&limit=10`,{cache:"no-store"}).then(r=>r.json()).then(p=>{setTrips(value=>tripPage===1?p.items:[...value,...p.items]);setTripMore(p.hasMore);});},[tab,tripPage]);
  useEffect(()=>{if(tab!=="points")return;fetch(`/api/account/points?page=${pointPage}&limit=15`,{cache:"no-store"}).then(r=>r.json()).then(p=>{setPoints(value=>pointPage===1?p.items:[...value,...p.items]);setPointMore(p.hasMore);});},[tab,pointPage]);
  if(!summary)return <p className="py-20 text-center">正在读取账户…</p>;
  const remove=async(id:string)=>{if(!confirm("确认删除这份攻略？删除后无法恢复。"))return;const response=await fetch(`/api/account/trips/${id}`,{method:"DELETE"});if(response.ok){setTrips(value=>value.filter(item=>item.id!==id));void loadSummary();}};
  return <div className="space-y-6"><section className="card rounded-3xl p-6"><p className="text-sm text-[#707a74]">我的一键出发</p><h1 className="mt-1 text-xl font-bold">{summary.emailMasked}</h1><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["可用点数",summary.points.available],["已生成攻略",summary.tripCount],["旅行海报",summary.posterCount],["累计使用",summary.points.lifetimeConsumed]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#eef3ec] p-4"><span className="text-xs text-[#65706a]">{label}</span><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div></section>
  <nav className="grid grid-cols-3 gap-2 rounded-2xl bg-white p-1.5 shadow-sm" aria-label="个人主页">{([["trips","我的攻略"],["points","点数记录"],["settings","账户设置"]] as const).map(([value,label])=><button key={value} onClick={()=>{setTab(value);trackEvent("account_tab_viewed",{pageName:"account",metadata:{tab:value}});}} className={`min-h-11 rounded-xl text-sm font-bold ${tab===value?"bg-[#245b46] text-white":"text-[#526159]"}`}>{label}</button>)}</nav>
  {tab==="trips"&&<section className="card rounded-3xl p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">我的攻略</h2><Link href="/#plan" className="rounded-full bg-[#245b46] px-4 py-2 text-sm font-bold text-white">规划新旅行</Link></div><div className="mt-4 space-y-3">{trips.map(item=><article key={item.id} className="rounded-2xl border border-black/8 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-xs text-[#707a74]">{item.destination} · {item.days}天 · {new Date(item.updatedAt).toLocaleDateString("zh-CN")}</p>{item.poster.status==="succeeded"&&<p className="mt-1 text-xs text-[#287057]">已生成 {item.poster.pages} 张旅行海报</p>}</div><span className="rounded-full bg-[#eef3ec] px-2 py-1 text-xs text-[#245b46]">{item.status==="completed"?"已完成":item.status==="generating"?"生成中":"未完成"}</span></div><div className="mt-3 flex flex-wrap gap-2"><Link href={`/trip/${item.id}`} className="rounded-full border px-3 py-2 text-xs font-bold">打开攻略</Link><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/trip/${item.id}`)} className="rounded-full border px-3 py-2 text-xs font-bold">复制分享链接</button>{item.poster.status==="succeeded"&&<Link href={`/trip/${item.id}#travel-poster`} className="rounded-full border px-3 py-2 text-xs font-bold">查看海报</Link>}<button onClick={()=>void remove(item.id)} className="rounded-full border border-red-200 px-3 py-2 text-xs font-bold text-red-700">删除</button></div></article>)}{!trips.length&&<p className="py-10 text-center text-sm text-[#707a74]">还没有已认领的攻略。</p>}</div>{tripMore&&<button onClick={()=>setTripPage(value=>value+1)} className="mx-auto mt-4 block rounded-full border px-5 py-2 text-sm font-bold">加载更多</button>}</section>}
  {tab==="points"&&<section className="card rounded-3xl p-5 sm:p-6"><h2 className="text-xl font-bold">点数记录</h2><p className="mt-2 text-sm text-[#65706a]">可用 {summary.points.available} 点，生成中预留 {summary.points.reserved} 点。点数购买即将开放。</p><div className="mt-4 divide-y">{points.map(row=><div key={row.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><strong>{row.label}</strong><p className="text-xs text-[#7b847e]">{new Date(row.createdAt).toLocaleString("zh-CN")}</p></div><span className={row.amount>=0?"text-[#287057]":"text-[#8a4b3b]"}>{row.amount>0?"+":""}{row.amount} · 余额 {row.balanceAfter}</span></div>)}{!points.length&&<p className="py-8 text-center text-sm text-[#707a74]">暂无点数记录。</p>}</div>{pointMore&&<button onClick={()=>setPointPage(value=>value+1)} className="mx-auto mt-4 block rounded-full border px-5 py-2 text-sm font-bold">加载更多</button>}</section>}
  {tab==="settings"&&<section className="card rounded-3xl p-6"><h2 className="text-xl font-bold">账户设置</h2><button className="mt-5 rounded-full border px-5 py-3 text-sm font-bold" onClick={async()=>{await fetch("/api/auth/session",{method:"DELETE"});location.href="/";}}>退出登录</button><button className="ml-2 mt-5 rounded-full border border-red-200 px-5 py-3 text-sm font-bold text-red-700" onClick={async()=>{if(!confirm("确认提交账户注销申请？生成中的海报会停止。"))return;const r=await fetch("/api/account/deletion-request",{method:"POST"});const p=await r.json();setMessage(p.message||"已提交");if(r.ok)location.href="/";}}>申请注销账户</button>{contactEmail?<p className="mt-5 text-sm text-[#65706a]">需要帮助？<a href={`mailto:${contactEmail}`} className="text-[#245b46] underline">联系我们</a></p>:<p className="mt-5 text-sm text-[#65706a]">需要帮助时，可先通过攻略页反馈联系我们。</p>}{message&&<p className="mt-3 text-sm">{message}</p>}</section>}</div>;
}
