"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {trackEvent} from "@/features/analytics/client";
import {logoutCurrentAccount} from "@/features/auth/logout";
import {PointsStore} from "@/features/account/points-store";
import {useSearchParams} from "next/navigation";
import {AppIcon} from "@/components/app-icons";
import {EmptyTripsIllustration} from "@/components/travel-illustrations";

type Summary={emailMasked:string;generationAccessMode:"normal"|"tester_unlimited";points:{available:number;reserved:number;lifetimeGranted:number;lifetimeConsumed:number};tripCount:number;posterCount:number};
type Trip={id:string;destination:string;days:number;title:string;status:string;updatedAt:string;poster:{status:string;pages:number}};
type Point={id:string;label:string;amount:number;balanceAfter:number;createdAt:string};
type Tab="trips"|"points"|"settings";

export function AccountClient({contactEmail}:{contactEmail:string|null}){
  const searchParams=useSearchParams();const initialTab=searchParams.get("tab")==="settings"?"settings":searchParams.get("tab")==="points"?"points":"trips";
  const[tab,setTab]=useState<Tab>(initialTab),[summary,setSummary]=useState<Summary|null>(null),[trips,setTrips]=useState<Trip[]>([]),[points,setPoints]=useState<Point[]>([]),[tripPage,setTripPage]=useState(1),[pointPage,setPointPage]=useState(1),[tripMore,setTripMore]=useState(false),[pointMore,setPointMore]=useState(false),[message,setMessage]=useState(""),[loggingOut,setLoggingOut]=useState(false);
  const loadSummary=useCallback(()=>fetch("/api/account/summary",{cache:"no-store"}).then(response=>{if(response.status===401){location.replace("/login?returnTo=/account");return null;}return response.ok?response.json():null;}).then(setSummary),[]);
  useEffect(()=>{void loadSummary();},[loadSummary]);
  useEffect(()=>{const signedOut=()=>{setSummary(null);setTrips([]);setPoints([]);location.replace("/?loggedOut=1");};let channel:BroadcastChannel|null=null;try{channel=new BroadcastChannel("yjchufa-auth");channel.addEventListener("message",event=>{if(event.data?.type==="logout_completed")signedOut();});}catch{/* unsupported */}const storage=(event:StorageEvent)=>{if(event.key==="yjchufa:auth-state"&&event.newValue?.includes("logout_completed"))signedOut();};const pageshow=(event:PageTransitionEvent)=>{if(event.persisted)void loadSummary();};const visible=()=>{if(document.visibilityState==="visible")void loadSummary();};window.addEventListener("storage",storage);window.addEventListener("pageshow",pageshow);document.addEventListener("visibilitychange",visible);return()=>{channel?.close();window.removeEventListener("storage",storage);window.removeEventListener("pageshow",pageshow);document.removeEventListener("visibilitychange",visible);};},[loadSummary]);
  useEffect(()=>{if(tab!=="trips")return;fetch(`/api/account/trips?page=${tripPage}&limit=10`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(payload=>{setTrips(value=>tripPage===1?payload.items:[...value,...payload.items]);setTripMore(payload.hasMore);}).catch(()=>setMessage("攻略读取失败，请刷新重试"));},[tab,tripPage]);
  useEffect(()=>{if(tab!=="points")return;fetch(`/api/account/points?page=${pointPage}&limit=15`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(payload=>{setPoints(value=>pointPage===1?payload.items:[...value,...payload.items]);setPointMore(payload.hasMore);}).catch(()=>setMessage("点数记录读取失败，请刷新重试"));},[tab,pointPage]);
  if(!summary)return <p className="py-20 text-center">正在读取账户…</p>;
  const remove=async(id:string)=>{if(!confirm("确认删除这份攻略？删除后无法恢复。"))return;const response=await fetch(`/api/account/trips/${id}`,{method:"DELETE"});if(response.ok){setTrips(value=>value.filter(item=>item.id!==id));void loadSummary();}};
  const logout=async()=>{if(!confirm("退出当前账号？"))return;setLoggingOut(true);setMessage("");try{await logoutCurrentAccount();setSummary(null);setTrips([]);setPoints([]);location.replace("/?loggedOut=1");}catch(error){setMessage(error instanceof Error?error.message:"退出失败，请稍后重试");setLoggingOut(false);}};
  return <div className="space-y-5">
    <section className="relative overflow-hidden rounded-[24px] bg-[var(--brand-primary-deep)] p-6 text-white shadow-[var(--shadow-feature)] sm:p-8"><div className="pointer-events-none absolute -right-12 -top-12 h-44 w-44 rounded-full bg-[var(--brand-lively)]/20"/><p className="relative text-sm font-medium text-white/65">我的一键出发</p><h1 className="relative mt-1 text-2xl font-bold tracking-[-.025em]">{summary.emailMasked}</h1>{summary.generationAccessMode==="tester_unlimited"&&<p className="relative mt-3 inline-flex rounded-full bg-[var(--warning-soft)] px-3 py-1 text-xs font-bold text-[var(--warning)]">测试权限已开启</p>}<div className="relative mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["可用点数",summary.points.available],["已生成攻略",summary.tripCount],["旅行海报",summary.posterCount],["累计使用",summary.points.lifetimeConsumed]].map(([label,value],index)=><div key={label} className={`rounded-2xl p-4 ${index===0?"bg-[var(--warning-soft)] text-[var(--text-strong)]":"bg-white/10"}`}><span className={`text-xs ${index===0?"text-[var(--warning)]":"text-white/65"}`}>{label}</span><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div></section>
    <nav className="grid grid-cols-3 gap-2 rounded-2xl border border-[var(--border-soft)] bg-white p-1.5 shadow-sm" aria-label="个人主页">{([['trips','我的攻略'],['points','点数记录'],['settings','账户设置']] as const).map(([value,label])=><button key={value} onClick={()=>{setTab(value);trackEvent("account_tab_viewed",{pageName:"account",metadata:{tab:value}});}} className={`min-h-11 rounded-xl text-sm font-semibold transition ${tab===value?'bg-[var(--brand-primary)] text-white shadow-sm':'text-[var(--text-secondary)] hover:bg-[var(--background-soft)]'}`}>{label}</button>)}</nav>
    {tab==="trips"&&<section className="app-card-primary p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-[var(--brand-primary)]">你的旅行</p><h2 className="mt-1 text-2xl font-bold">最近行程</h2></div><Link href="/#plan" className="btn-primary px-4 py-2 text-sm"><AppIcon name="depart" className="mr-2 h-4 w-4"/>安排新旅行</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{trips.map((item,index)=><article key={item.id} className="app-card-secondary overflow-hidden"><div className={`h-2 ${index%3===0?"bg-[var(--brand-lively)]":index%3===1?"bg-[var(--accent-warm)]":"bg-[var(--info)]"}`}/><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">{item.title}</h3><p className="mt-1 text-xs text-[#707a74]">{item.destination} · {item.days}天 · {new Date(item.updatedAt).toLocaleDateString("zh-CN")}</p>{item.poster.status==="succeeded"&&<p className="mt-2 text-xs font-semibold text-[#287057]">已有 {item.poster.pages} 张旅行海报</p>}</div><span className="rounded-full bg-[#eef3ec] px-2 py-1 text-xs text-[#245b46]">{item.status==="completed"?"已完成":item.status==="generating"?"生成中":"未完成"}</span></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/trip/${item.id}`} className="btn-secondary px-3 py-2 text-xs">查看</Link><button onClick={()=>navigator.clipboard.writeText(`${location.origin}/trip/${item.id}`)} className="btn-secondary px-3 py-2 text-xs"><AppIcon name="share" className="mr-1 h-4 w-4"/>分享</button>{item.poster.status==="succeeded"&&<Link href={`/trip/${item.id}#travel-poster`} className="btn-secondary px-3 py-2 text-xs">海报</Link>}<button onClick={()=>void remove(item.id)} className="ml-auto px-2 py-2 text-xs font-semibold text-[var(--error)]">删除</button></div></div></article>)}{!trips.length&&<div className="col-span-full py-5 text-center"><EmptyTripsIllustration className="mx-auto w-full max-w-xs"/><h3 className="mt-5 text-lg font-semibold">还没有行程</h3><p className="mt-1 text-sm text-[var(--text-secondary)]">去安排第一趟旅行吧。</p></div>}</div>{tripMore&&<button onClick={()=>setTripPage(value=>value+1)} className="btn-secondary mx-auto mt-5 flex px-5 py-2 text-sm">加载更多</button>}</section>}
    {tab==="points"&&<section className="card rounded-3xl p-5 sm:p-6"><h2 className="text-xl font-bold">点数记录</h2><p className="mt-2 text-sm text-[#65706a]">可用 {summary.points.available} 点，生成中预留 {summary.points.reserved} 点。</p><PointsStore/><div className="mt-4 divide-y">{points.map(row=><div key={row.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><strong>{row.label}</strong><p className="text-xs text-[#7b847e]">{new Date(row.createdAt).toLocaleString("zh-CN")}</p></div><span className={row.amount>=0?"text-[#287057]":"text-[#8a4b3b]"}>{row.amount>0?"+":""}{row.amount} · 余额 {row.balanceAfter}</span></div>)}{!points.length&&<p className="py-8 text-center text-sm text-[#707a74]">暂无点数记录。</p>}</div>{pointMore&&<button onClick={()=>setPointPage(value=>value+1)} className="mx-auto mt-4 block rounded-full border px-5 py-2 text-sm font-bold">加载更多</button>}</section>}
    {tab==="settings"&&<section className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><div className="app-card-primary p-6"><p className="text-sm font-bold text-[var(--brand-primary)]">常用入口</p><h2 className="mt-1 text-2xl font-bold">我的</h2><div className="mt-5 divide-y divide-[var(--border-soft)]">{[["poster","我的海报","查看已生成的旅行作品","/account?tab=trips"],["points","点数与记录","查看余额和使用明细","/account?tab=points"],["support","联系支持",contactEmail||"通过攻略页反馈联系我们",contactEmail?`mailto:${contactEmail}`:"/about"]].map(([icon,title,body,href])=><Link key={title} href={href} className="flex min-h-20 items-center gap-4 py-3"><span className="icon-bubble"><AppIcon name={icon as "poster"}/></span><span className="min-w-0 flex-1"><strong className="block">{title}</strong><small className="text-[var(--text-secondary)]">{body}</small></span><AppIcon name="chevron" className="h-5 w-5 text-[var(--text-muted)]"/></Link>)}</div></div><div className="app-card-secondary p-6"><h2 className="text-lg font-semibold">账户设置</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">退出只会结束当前设备登录，不会删除行程或点数。</p><button disabled={loggingOut} className="btn-secondary mt-5 w-full px-5 py-3 text-sm disabled:opacity-50" onClick={()=>void logout()}>{loggingOut?"正在退出…":"退出登录"}</button><button className="mt-8 w-full px-4 py-3 text-sm font-semibold text-[var(--error)]" onClick={async()=>{if(!confirm("确认提交账户注销申请？生成中的海报会停止。"))return;const response=await fetch("/api/account/deletion-request",{method:"POST"});const payload=await response.json();setMessage(payload.message||"已提交");if(response.ok)location.href="/";}}>申请注销账户</button></div></section>}
    {message&&<p role="status" className="status-warning rounded-xl p-3 text-sm">{message}</p>}
  </div>;
}
