"use client";

import { useState } from "react";
import { hangzhouSample } from "./hangzhou-sample";

export function HangzhouSamplePreview() {
  const [expanded, setExpanded] = useState(false);
  function backToPlan() {
    document.getElementById("plan")?.scrollIntoView({ behavior: "smooth", block: "start" });
    window.setTimeout(() => document.getElementById("trip-destination")?.focus({ preventScroll: true }), 450);
  }
  return <section className="mt-12 sm:mt-16" aria-labelledby="sample-title"><div className="mb-5"><span className="inline-flex rounded-full bg-[#f0e4cd] px-3 py-1 text-xs font-bold text-[#8a5b24]">示例攻略</span><h2 id="sample-title" className="mt-3 text-2xl font-bold sm:text-3xl">看看生成后的旅行计划</h2><p className="mt-2 text-sm text-[#65706a]">先看一份杭州三日安排示例</p></div><div className="card overflow-hidden rounded-[2rem]"><header className="bg-[#204f3c] p-5 text-white sm:p-8"><p className="text-sm font-semibold text-white/65">杭州 · 3天</p><h3 className="mt-2 text-2xl font-bold sm:text-3xl">{hangzhouSample.title}</h3><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm text-white/80"><span>适合：{hangzhouSample.audience}</span><span>风格：{hangzhouSample.style}</span><span>偏好：{hangzhouSample.priorities.join("、")}</span></div></header><div className="p-5 sm:p-8"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["整体强度",hangzhouSample.intensity],["建议住宿",hangzhouSample.stayArea],["主要活动",hangzhouSample.mainActivities],["第一天",hangzhouSample.days[0].route]].map(([label,value], index) => <div key={label} className={`rounded-2xl bg-[#f4f6f1] p-4 ${index === 3 ? "col-span-2 sm:col-span-1" : ""}`}><p className="text-xs font-bold text-[#7b847e]">{label}</p><p className="mt-2 text-sm font-semibold leading-6">{value}</p></div>)}</div>{expanded && <div className="mt-6 space-y-4 border-t border-black/5 pt-6">{hangzhouSample.days.map((day) => <article key={day.day} className="rounded-2xl border border-black/7 bg-white p-4 sm:p-5"><p className="text-xs font-bold text-[#287057]">DAY {day.day}</p><h4 className="mt-2 text-lg font-bold">{day.title}</h4><p className="mt-2 text-sm font-semibold text-[#4f5f57]">{day.route}</p><p className="mt-2 text-sm leading-6 text-[#707a74]">{day.detail}</p></article>)}</div>}<button type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded} className="mt-6 w-full rounded-full border border-[#245b46]/20 px-5 py-3 text-sm font-bold text-[#245b46]">{expanded ? "收起示例" : "查看完整三日示例"}</button><button type="button" onClick={backToPlan} className="mt-3 w-full rounded-full bg-[#245b46] px-5 py-3 text-sm font-bold text-white">按这样的方式规划我的旅行</button></div></div></section>;
}
