"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";
import { tripImageTaskSchema, travelPosterSpecSchema, type TripImageTask } from "@/schemas/trip-image";
import { renderTravelPosters } from "./premium-image-renderer";
import { trackEvent } from "@/features/analytics/client";

type ApiPayload = { tasks: unknown[]; remaining: number; requiredPoints?:number|null; paymentsEnabled?:boolean; authenticated?: boolean; task?: unknown; error?: { message?: string } };
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500); }

export function PremiumTripImages({ tripId, tripVersion, canEdit, destination, daysCount, placement = "top" }: { tripId: string; tripVersion: number; canEdit: boolean; destination: string; daysCount: number; placement?: "top" | "bottom" }) {
  const [tasks, setTasks] = useState<TripImageTask[]>([]); const [remaining, setRemaining] = useState(0); const [requiredPoints,setRequiredPoints]=useState(Math.ceil(daysCount/2)); const [paymentsEnabled,setPaymentsEnabled]=useState(false); const [authenticated,setAuthenticated]=useState(false); const [loginOpen,setLoginOpen]=useState(false); const [email,setEmail]=useState(""); const [legalAccepted,setLegalAccepted]=useState(false); const [loginMessage,setLoginMessage]=useState(""); const [historyLoading, setHistoryLoading] = useState(true); const [open, setOpen] = useState(false); const [exampleOpen,setExampleOpen]=useState(false); const [step, setStep] = useState<"confirm" | "generating" | "preview">("confirm"); const [error, setError] = useState(""); const [blobs, setBlobs] = useState<Blob[]>([]); const [previews, setPreviews] = useState<string[]>([]);
  const load = useCallback(async () => { try { const response = await fetch(`/api/trips/${tripId}/images`, { cache: "no-store" }); const payload = await response.json() as ApiPayload; if (!response.ok) return; setAuthenticated(Boolean(payload.authenticated)); const parsed: TripImageTask[]=[]; for(const task of payload.tasks){const item=tripImageTaskSchema.safeParse(task);if(item.success&&item.data.imageType==="travel_poster")parsed.push(item.data);} setTasks(parsed); setRemaining(payload.remaining);setRequiredPoints(payload.requiredPoints??Math.ceil(daysCount/2));setPaymentsEnabled(Boolean(payload.paymentsEnabled)); return parsed; } catch { return undefined; } finally { setHistoryLoading(false); } }, [tripId,daysCount]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]); useEffect(() => () => previews.forEach(URL.revokeObjectURL), [previews]);
  const current = useMemo(() => tasks.find((task) => task.templateVersion === "shaoxing_timeline_v2" && task.tripVersion === tripVersion && task.status === "succeeded") || tasks.find((task) => task.templateVersion === "shaoxing_timeline_v2" && task.status === "succeeded"), [tasks, tripVersion]);
  const legacy = useMemo(() => tasks.find((task) => task.templateVersion === "travel_poster_v1" && task.status === "succeeded"), [tasks]);
  const running = useMemo(() => tasks.find((task) => task.templateVersion === "shaoxing_timeline_v2" && task.tripVersion === tripVersion && task.status === "running"), [tasks, tripVersion]);
  const expectedPages = Math.ceil(daysCount / 2);
  async function requestLogin(){setLoginMessage("");try{const response=await fetch("/api/auth/email/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,returnTo:`/trip/${tripId}`,legalAccepted})});const payload=await response.json() as {message?:string};setLoginMessage(payload.message||"如果邮箱可用，登录链接会很快发出。");}catch{setLoginMessage("暂时无法发送，请稍后再试。");}}
  const preview = useCallback(async (task: TripImageTask) => { const parsed = travelPosterSpecSchema.safeParse(task.output); if (!parsed.success) return; setStep("generating"); setError(""); try { const images = await renderTravelPosters(parsed.data); setBlobs(images); setPreviews(images.map(URL.createObjectURL)); setStep("preview"); } catch { setError("海报排版失败，请稍后重试"); setStep("confirm"); } }, []);
  useEffect(() => { if (!open || !running) return; const timer=window.setInterval(async()=>{const fresh=await load();const ready=fresh?.find(task=>task.tripVersion===tripVersion&&task.status==="succeeded");if(ready)await preview(ready);},3000); return()=>window.clearInterval(timer); }, [open,running,load,tripVersion,preview]);
  async function generate() { setStep("generating"); setError(""); try { const response = await fetch(`/api/trips/${tripId}/images`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ imageType: "travel_poster", aspectRatio: "3:4", idempotencyKey: crypto.randomUUID() }) }); const payload = await response.json() as ApiPayload; if (!response.ok) throw new Error(payload.error?.message || "暂时没能生成这张海报，免费机会不会被扣除，请稍后再试。"); const parsed = tripImageTaskSchema.parse(payload.task); setTasks((value) => [parsed, ...value.filter((task) => task.id !== parsed.id)]); setRemaining(payload.remaining); if(parsed.status==="succeeded")await preview(parsed); } catch (cause) { setError(cause instanceof Error ? cause.message : "暂时没能生成这张海报，免费机会不会被扣除，请稍后再试。"); setStep("confirm"); } }
  async function saveAll() { const files = blobs.map((blob, index) => new File([blob], `一键出发-${destination}-旅行海报-${index + 1}.jpg`, { type: "image/jpeg" })); if (navigator.share && navigator.canShare?.({ files })) { try { await navigator.share({ files, title: `${destination}旅行海报` }); trackEvent("travel_poster_shared", { pageName: "trip", tripId, metadata: { pages: files.length } }); return; } catch (cause) { if (cause instanceof DOMException && cause.name === "AbortError") return; } } blobs.forEach((blob, index) => download(blob, files[index]!.name)); trackEvent("travel_poster_saved", { pageName: "trip", tripId, metadata: { pages: files.length } }); }
  if (!canEdit && tasks.length === 0) return null;
  return <section id={placement === "top" ? "travel-poster" : undefined} className="mt-5 border-t border-black/5 pt-5">
    <div className="flex flex-col gap-2 sm:flex-row"><button type="button" disabled={historyLoading} onClick={() => { trackEvent(`poster_generate_click_${placement}`,{pageName:"trip",tripId}); if(!authenticated&&!current){trackEvent("poster_login_prompt_shown",{pageName:"trip",tripId});setLoginOpen(true);return;} setOpen(true); setError(""); if (current) void preview(current); else if(running)setStep("generating"); else setStep("confirm"); }} className="group w-full rounded-2xl bg-[#245b46] px-5 py-4 text-left text-white shadow-[0_12px_28px_rgba(36,91,70,.18)] disabled:opacity-60 sm:w-auto sm:min-w-80"><span className="flex items-center gap-3"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6 text-[#ffd45a]" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 17.5 8.5 13l3 3L17 8.5"/><path d="M14 8.5h3v3"/><path d="M5 5.5h4M7 3.5v4"/></svg><span><strong className="block text-base">{historyLoading ? "正在读取海报…" : running ? "海报生成中" : current ? "查看我的旅行海报" : canEdit ? "生成精美旅行海报" : "查看旅行海报"}</strong><span className="mt-1 block text-xs text-white/75">{placement === "bottom" ? "把这趟行程变成一份值得保存和分享的旅行作品" : "把你的行程变成一份值得分享的旅行作品"}</span></span></span></button><button type="button" onClick={()=>{trackEvent(`poster_example_open_${placement}`,{pageName:"trip",tripId});setExampleOpen(true);}} className="min-h-12 rounded-2xl border border-[#245b46]/20 bg-white px-5 py-3 text-sm font-bold text-[#245b46]">查看示例</button></div>
    {canEdit && !historyLoading && <p className="mt-2 text-xs text-[#707a74]">{current ? "已生成，可随时查看和保存" : `本次需要 ${requiredPoints} 点 · 当前 ${remaining} 点`}</p>}
    {exampleOpen && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/55 p-4" role="dialog" aria-modal="true" aria-label="旅行海报示例"><div className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-[#f7f5ef] p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold text-[#204f3c]">旅行海报示例</h2><p className="text-xs text-[#65706a]">示例仅展示成品效果，不调用 AI、不消耗额度。</p></div><button type="button" onClick={()=>setExampleOpen(false)} aria-label="关闭示例" className="min-h-11 min-w-11 rounded-full bg-white text-xl">×</button></div><Image unoptimized src="/examples/shaoxing-travel-poster-example.jpg" width={1200} height={1800} alt="绍兴两天一晚旅行海报示例" className="h-auto w-full rounded-2xl"/></div></div>}
    {legacy && <button type="button" onClick={()=>{setOpen(true);void preview(legacy);}} className="mt-2 block text-xs text-[#707a74] underline underline-offset-2">查看旧版海报（旧版）</button>}
    {open && <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/45 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label="旅行海报"><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl bg-[#f7f5ef] p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-bold text-[#204f3c]">生成你的旅行海报</h2><p className="mt-1 text-sm text-[#65706a]">海报会根据当前行程生成，路线需要调整的话可以先返回修改。</p></div><button type="button" onClick={() => setOpen(false)} aria-label="关闭海报面板" className="min-h-11 min-w-11 rounded-full bg-white text-xl">×</button></div>
      {step === "confirm" && <div className="mt-6"><div className="grid grid-cols-3 gap-2 rounded-2xl bg-white p-4 text-center"><div><span className="block text-xs text-[#707a74]">目的地</span><strong>{destination}</strong></div><div><span className="block text-xs text-[#707a74]">天数</span><strong>{daysCount}天</strong></div><div><span className="block text-xs text-[#707a74]">预计</span><strong>{expectedPages}张</strong></div></div><p className="mt-4 rounded-2xl bg-[#fff2d9] p-4 text-sm text-[#7a5524]">生成需要 {requiredPoints} 点，当前余额 {remaining} 点。{!paymentsEnabled&&remaining<requiredPoints?" 点数购买即将开放。":""}</p>{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex gap-3"><button onClick={() => setOpen(false)} className="flex-1 rounded-full border bg-white px-4 py-3 font-bold">返回调整行程</button><button onClick={generate} disabled={!canEdit || remaining < requiredPoints} className="flex-1 rounded-full bg-[#245b46] px-4 py-3 font-bold text-white disabled:opacity-40">确认生成海报</button></div></div>}
      {step === "generating" && <div className="py-16 text-center"><div className="mx-auto flex w-fit gap-2" aria-hidden="true"><i className="h-3 w-3 animate-pulse rounded-full bg-[#ffd45a]"/><i className="h-3 w-3 animate-pulse rounded-full bg-[#ffd45a] [animation-delay:.25s]"/><i className="h-3 w-3 animate-pulse rounded-full bg-[#ffd45a] [animation-delay:.5s]"/></div><p className="mt-6 font-bold text-[#204f3c]">正在把你的行程变成旅行海报</p><p className="mt-2 text-sm text-[#707a74]">复杂行程可能需要约1～2分钟，请稍等一下。</p></div>}
      {step === "preview" && <div className="mt-6"><p className="mb-3 text-sm text-[#65706a]">共生成 {previews.length} 张海报</p><div className="grid gap-5 sm:grid-cols-2">{previews.map((url, index) => <div key={url}><Image unoptimized src={url} width={720} height={1080} alt={`旅行海报第${index + 1}页`} className="h-auto w-full rounded-2xl shadow-md"/><button onClick={() => download(blobs[index]!, `一键出发-${destination}-旅行海报-${index + 1}.jpg`)} className="mt-2 w-full rounded-full border bg-white px-4 py-2 text-sm font-bold">保存第 {index + 1} 张</button></div>)}</div>{current && current.tripVersion !== tripVersion && <p className="mt-4 rounded-xl bg-[#fff2d9] p-3 text-sm text-[#7a5524]">这组海报基于修改前的行程生成，当前行程已更新。</p>}<div className="mt-5 flex gap-3"><button onClick={saveAll} className="flex-1 rounded-full bg-[#245b46] px-5 py-3 font-bold text-white">全部保存</button><button onClick={() => setOpen(false)} className="rounded-full border bg-white px-5 py-3 font-bold">返回攻略</button></div></div>}
    </div></div>}
    {loginOpen && <div className="fixed inset-0 z-[95] flex items-end justify-center bg-black/55 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label="登录后生成海报"><div className="w-full max-w-md rounded-t-3xl bg-white p-6 sm:rounded-3xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold text-[#204f3c]">登录后生成旅行海报</h2><p className="mt-1 text-sm text-[#65706a]">普通攻略仍可匿名使用，只有旅行海报需要邮箱登录。</p></div><button onClick={()=>setLoginOpen(false)} aria-label="关闭登录" className="min-h-11 min-w-11 rounded-full bg-[#f4f6f1]">×</button></div><label className="mt-5 block text-sm font-bold">邮箱</label><input value={email} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="email" className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="you@example.com"/><label className="mt-3 flex items-start gap-2 text-xs leading-5"><input type="checkbox" checked={legalAccepted} onChange={event=>setLegalAccepted(event.target.checked)} className="mt-1"/><span>我已阅读并同意服务协议和隐私政策</span></label><button onClick={requestLogin} disabled={!email||!legalAccepted} className="mt-4 w-full rounded-full bg-[#245b46] px-5 py-3 font-bold text-white disabled:opacity-40">发送登录链接</button>{loginMessage&&<p className="mt-3 rounded-xl bg-[#eef3ec] p-3 text-sm text-[#245b46]">{loginMessage}</p>}<p className="mt-3 text-xs leading-5 text-[#7b847e]">登录链接15分钟内有效且只能使用一次，登录后会回到当前攻略。</p></div></div>}
  </section>;
}
