"use client";

import { useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { tripImageTaskSchema, type TripImageAspectRatio, type TripImageTask } from "@/schemas/trip-image";
import { renderPremiumTripImages } from "./premium-image-renderer";
import { trackEvent } from "@/features/analytics/client";

type ApiPayload = { tasks: unknown[]; canGenerate: boolean; remaining: number; task?: unknown; reused?: boolean; error?: { message?: string } };
const ratios: Array<{ value: TripImageAspectRatio; label: string; note: string }> = [{ value: "3:4", label: "3:4", note: "推荐" }, { value: "9:16", label: "9:16", note: "手机长图" }, { value: "1:1", label: "1:1", note: "社交封面" }];
function newKey() { return crypto.randomUUID(); }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500); }

export function PremiumTripImages({ tripId, tripVersion, canEdit, destination }: { tripId: string; tripVersion: number; canEdit: boolean; destination: string }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState<"confirm" | "ratio" | "preview">("confirm"); const [ratio, setRatio] = useState<TripImageAspectRatio>("3:4");
  const [tasks, setTasks] = useState<TripImageTask[]>([]); const [remaining, setRemaining] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [blobs, setBlobs] = useState<Blob[]>([]); const [previews, setPreviews] = useState<string[]>([]);
  const [historyLoading, setHistoryLoading] = useState(true);
  const load = useCallback(async () => { try { const response = await fetch(`/api/trips/${tripId}/images`, { cache: "no-store" }); const payload = await response.json() as ApiPayload; if (!response.ok) return; const parsed = payload.tasks.map((task) => tripImageTaskSchema.safeParse(task)).filter((item) => item.success).map((item) => item.data); setTasks(parsed); setRemaining(payload.remaining); } catch { /* image history never blocks the trip */ } finally { setHistoryLoading(false); } }, [tripId]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  useEffect(() => () => previews.forEach((url) => URL.revokeObjectURL(url)), [previews]);
  const current = tasks.find((task) => task.tripVersion === tripVersion && task.aspectRatio === ratio && task.status === "succeeded") || tasks.find((task) => task.status === "succeeded");
  async function preview(task: TripImageTask) { if (!task.output) return; setLoading(true); setError(""); try { const rendered = await renderPremiumTripImages(task.output); setBlobs(rendered); setPreviews(rendered.map((blob) => URL.createObjectURL(blob))); setStep("preview"); } catch { setError("图片排版失败，请稍后重试"); } finally { setLoading(false); } }
  async function generate() { if (loading) return; setLoading(true); setError(""); try { const response = await fetch(`/api/trips/${tripId}/images`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ imageType: "premium_trip", aspectRatio: ratio, idempotencyKey: newKey() }) }); const payload = await response.json() as ApiPayload; if (!response.ok) throw new Error(payload.error?.message || "图片生成失败"); const parsed = tripImageTaskSchema.parse(payload.task); setTasks((value) => [parsed, ...value.filter((task) => task.id !== parsed.id)]); setRemaining(payload.remaining ?? 0); await preview(parsed); } catch (cause) { setError(cause instanceof Error ? cause.message : "图片生成失败"); setLoading(false); } }
  async function saveAll() { if (!blobs.length) return; const files = blobs.map((blob, index) => new File([blob], `一键出发-${destination}-${ratio.replace(":", "x")}-${index + 1}.png`, { type: "image/png" })); if (navigator.share && navigator.canShare?.({ files })) { try { await navigator.share({ files, title: `${destination}旅行图片版` }); trackEvent("premium_image_shared", { pageName: "trip", tripId, metadata: { ratio, pages: files.length } }); return; } catch (cause) { if (cause instanceof DOMException && cause.name === "AbortError") return; } } blobs.forEach((blob, index) => download(blob, files[index]!.name)); trackEvent("premium_image_saved", { pageName: "trip", tripId, metadata: { ratio, pages: blobs.length } }); }
  if (!canEdit && tasks.length === 0) return null;
  return <section id="premium-trip-images" className="mt-5 border-t border-black/5 pt-5">
    <button type="button" disabled={historyLoading} onClick={() => { setOpen(true); setError(""); if (current) void preview(current); else setStep("confirm"); }} className="rounded-full border border-[#245b46]/20 bg-white px-5 py-2.5 text-sm font-bold text-[#245b46] disabled:opacity-60">{historyLoading ? "正在读取图片…" : canEdit ? "生成精美图片版" : "查看精美图片版"}</button>
    {canEdit && <p className="mt-2 text-xs text-[#707a74]">适合保存和分享，建议确认路线后再生成</p>}
    {open && <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label="精美旅行图片">
      <div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-[#f7f5ef] p-5 shadow-2xl sm:rounded-3xl sm:p-7">
        <div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-[#204f3c]">精美旅行图片</h2><p className="mt-1 text-sm text-[#65706a]">模板排版，不会重新改写你的行程。</p></div><button type="button" onClick={() => setOpen(false)} aria-label="关闭图片面板" className="min-h-11 min-w-11 rounded-full bg-white text-xl">×</button></div>
        {step === "confirm" && <div className="mt-6"><p className="font-bold">生成前建议先确认</p><ul className="mt-3 space-y-2 text-sm text-[#526159]"><li>· 路线是否满意</li><li>· 天数是否正确</li><li>· 是否还有活动需要调整</li></ul><p className="mt-5 rounded-2xl bg-[#fff2d9] p-4 text-sm text-[#7a5524]">{remaining > 0 ? `你有 ${remaining} 次免费精美图片生成机会` : "免费图片机会已使用，更多图片生成方式正在准备中"}</p><div className="mt-6 flex gap-3"><button type="button" onClick={() => setOpen(false)} className="flex-1 rounded-full border bg-white px-4 py-3 font-bold">返回继续调整</button><button type="button" onClick={() => setStep("ratio")} disabled={!canEdit || remaining < 1} className="flex-1 rounded-full bg-[#245b46] px-4 py-3 font-bold text-white disabled:opacity-40">确认生成图片</button></div></div>}
        {step === "ratio" && <div className="mt-6"><p className="font-bold">选择图片比例</p><div className="mt-3 grid grid-cols-3 gap-2">{ratios.map((item) => <button key={item.value} type="button" onClick={() => setRatio(item.value)} className={`rounded-2xl border p-3 text-center ${ratio === item.value ? "border-[#245b46] bg-[#e5ede6]" : "bg-white"}`}><strong className="block">{item.label}</strong><span className="mt-1 block text-xs text-[#707a74]">{item.note}</span></button>)}</div><button type="button" onClick={generate} disabled={loading} className="mt-6 w-full rounded-full bg-[#245b46] px-5 py-3 font-bold text-white disabled:opacity-50">{loading ? "正在整理你的旅行计划图……" : "生成图片"}</button></div>}
        {step === "preview" && <div className="mt-6"><div className="grid gap-4 sm:grid-cols-2">{previews.map((url, index) => <Image unoptimized key={url} src={url} width={540} height={ratio === "9:16" ? 960 : ratio === "3:4" ? 720 : 540} alt={`旅行图片第${index + 1}页`} className="h-auto w-full rounded-2xl border bg-white shadow-sm" />)}</div>{current && current.tripVersion !== tripVersion && <p className="mt-4 rounded-xl bg-[#fff2d9] p-3 text-sm text-[#7a5524]">这组图片基于修改前的行程生成。当前路线已更新，需要新的图片额度才能生成新版。</p>}<div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={saveAll} className="flex-1 rounded-full bg-[#245b46] px-5 py-3 font-bold text-white">一键保存全部</button>{canEdit && <button type="button" onClick={() => setStep("ratio")} className="rounded-full border bg-white px-5 py-3 font-bold">换个比例</button>}<button type="button" onClick={() => setOpen(false)} className="rounded-full border bg-white px-5 py-3 font-bold">返回攻略</button></div></div>}
        {loading && step !== "ratio" && <p className="mt-5 text-center text-sm text-[#65706a]">正在整理你的旅行计划图</p>}{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      </div>
    </div>}
  </section>;
}
