import type { DayPlan, TripPlan } from "@/types/trip";

const intensity = { easy: "轻松", moderate: "适中", intense: "充实" };
const method = { walk: "步行", public_transport: "公共交通", taxi: "打车", mixed: "组合交通" };

export function TripPlanView({ plan, onReviseDay, notice, canUndo, onUndo }: { plan: TripPlan; onReviseDay?: (day: DayPlan) => void; notice?: string[]; canUndo?: boolean; onUndo?: () => void }) {
  const budgetLabel = plan.budget.estimateType === "exact" && plan.budget.estimatedTotal !== null
    ? `预计 ¥${plan.budget.estimatedTotal}`
    : plan.budget.estimateType === "range" && plan.budget.estimatedRange
      ? `参考 ¥${plan.budget.estimatedRange.min}–${plan.budget.estimatedRange.max}`
      : "按偏好灵活安排";
  return <main className="pb-20">
    <section className="bg-[#204f3c] py-14 text-white sm:py-20"><div className="page-shell"><p className="text-sm font-semibold text-white/65">{plan.destination.city} · {plan.days.length}天</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">{plan.title}</h1><p className="mt-5 max-w-2xl leading-7 text-white/75">{plan.summary}</p><div className="mt-8 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-white/10 px-4 py-2">节奏：{plan.strategy.pace}</span><span className="rounded-full bg-white/10 px-4 py-2">预算：{budgetLabel}</span><span className="rounded-full bg-white/10 px-4 py-2">住在：{plan.strategy.recommendedStayArea}</span></div></div></section>
    {((notice && notice.length > 0) || canUndo) && <div className="page-shell mt-6 flex flex-col gap-3 rounded-2xl border border-[#245b46]/15 bg-[#eaf2ed] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[#245b46]">{canUndo ? "已调整当天行程" : "行程已恢复"}</p><p className="mt-1 text-sm text-[#53635b]">{notice?.length ? notice.join("；") : "最近一次修改已保存在当前浏览器，可撤销。"}</p></div>{canUndo && onUndo && <button onClick={onUndo} className="shrink-0 rounded-full border border-[#245b46]/20 bg-white px-4 py-2 text-sm font-bold text-[#245b46]">撤销本次修改</button>}</div>}
    <div className="page-shell mt-8 grid gap-6 lg:grid-cols-[1fr_300px]">
      <div className="space-y-6">{plan.days.map((day) => <article key={day.dayNumber} className="card overflow-hidden rounded-3xl"><header className="border-b border-black/5 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#287057]">DAY {day.dayNumber}{day.date ? ` · ${day.date}` : ""}</p><h2 className="mt-2 text-2xl font-bold">{day.title}</h2><p className="mt-1 text-[#6f7973]">{day.theme}</p></div>{onReviseDay && <button onClick={() => onReviseDay(day)} className="rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-semibold text-[#245b46] hover:border-[#245b46]/40">调整这一天</button>}</div><div className="mt-5 flex flex-wrap gap-4 text-xs font-semibold text-[#65706a]"><span>强度：{intensity[day.intensity]}</span><span>步行约 {day.estimatedWalkingKm} km</span>{day.estimatedCost !== null && <span>预计 ¥{day.estimatedCost}</span>}</div></header><div className="p-5 sm:p-7">{day.activities.map((activity, index) => <div key={activity.id} className="relative flex gap-4 pb-8 last:pb-0"><div className="flex w-12 shrink-0 flex-col items-center"><span className="text-xs font-bold text-[#287057]">{activity.startTime}</span>{index < day.activities.length - 1 && <span className="mt-2 h-full w-px bg-[#dbe4de]" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-bold">{activity.name}</h3><span className="text-xs text-[#7b847e]">{activity.area} · {activity.durationMinutes}分钟</span></div><p className="mt-2 text-sm leading-6 text-[#65706a]">{activity.reason}</p>{activity.transportToNext && <p className="mt-3 rounded-xl bg-[#f2f5f0] px-3 py-2 text-xs text-[#566159]">下一站：{method[activity.transportToNext.method]}约 {activity.transportToNext.durationMinutes} 分钟 · {activity.transportToNext.description}</p>}</div></div>)}<div className="mt-5 rounded-2xl bg-[#fff7e9] p-4"><p className="text-sm font-bold text-[#9a6223]">今日提醒</p><ul className="mt-2 space-y-1 text-sm leading-6 text-[#785f41]">{day.dayTips.map((tip) => <li key={tip}>· {tip}</li>)}</ul></div></div></article>)}</div>
      <aside className="space-y-5 lg:sticky lg:top-6 lg:self-start"><section className="card rounded-3xl p-6"><h2 className="font-bold">住在哪里</h2><p className="mt-3 text-lg font-bold text-[#245b46]">{plan.strategy.recommendedStayArea}</p><p className="mt-2 text-sm leading-6 text-[#65706a]">{plan.strategy.stayReason}</p></section><section className="card rounded-3xl p-6"><h2 className="font-bold">预算概览</h2><div className="mt-4"><strong className="text-xl">{budgetLabel}</strong></div><p className="mt-3 text-xs leading-5 text-[#7b847e]">{plan.budget.notes}</p>{plan.budget.includedItems.length > 0 && <p className="mt-3 text-xs leading-5 text-[#65706a]">包含：{plan.budget.includedItems.join("、")}</p>}{plan.budget.excludedItems.length > 0 && <p className="mt-1 text-xs leading-5 text-[#65706a]">不含：{plan.budget.excludedItems.join("、")}</p>}</section><section className="rounded-3xl bg-[#f0e4cd] p-6"><h2 className="font-bold">出发前确认</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-[#63553f]">{plan.generalTips.map((tip) => <li key={tip}>· {tip}</li>)}</ul></section></aside>
    </div><p className="page-shell mt-8 text-center text-xs leading-5 text-[#858d88]">{plan.dataDisclaimer}</p>
  </main>;
}
