"use client";
import { FormEvent, useEffect, useState } from "react";

type Row = { id: string; tripId: string; rating: string; tags: string[]; comment: string | null; createdAt: string; kind: string; dayNumber: number | null; destination: string; style: string };
type Data = { stats: { total: number; helpful: number; usable: number; notHelpful: number; tagCounts: [string,number][] }; rows: Row[]; page: number; pages: number };
const ratingLabel: Record<string,string> = { helpful: "很有帮助", usable: "基本可用", not_helpful: "不太有用" };

export function FeedbackAdmin({ authorized, configured }: { authorized: boolean; configured: boolean }) {
  const [loggedIn,setLoggedIn]=useState(authorized); const [code,setCode]=useState(""); const [error,setError]=useState(""); const [data,setData]=useState<Data|null>(null); const [query,setQuery]=useState("kind=all&page=1");
  useEffect(()=>{ if(loggedIn) fetch(`/api/admin/feedback?${query}`).then(async(response)=>{if(!response.ok) throw new Error();return response.json();}).then(setData).catch(()=>setError("反馈数据加载失败")); },[loggedIn,query]);
  async function login(event: FormEvent){event.preventDefault();setError("");const response=await fetch("/api/admin/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});if(response.ok){setLoggedIn(true);setCode("");}else setError((await response.json()).error||"登录失败");}
  if(!configured) return <main className="page-shell py-20"><div className="card mx-auto max-w-lg rounded-3xl p-8"><h1 className="text-2xl font-bold">反馈后台尚未启用</h1><p className="mt-3 text-sm text-[#65706a]">请在 Vercel Production 环境配置 ADMIN_ACCESS_CODE 并重新部署。</p></div></main>;
  if(!loggedIn) return <main className="page-shell py-20"><form onSubmit={login} className="card mx-auto max-w-md rounded-3xl p-8"><h1 className="text-2xl font-bold">反馈管理</h1><label className="mt-6 block text-sm font-bold">管理访问码<input type="password" value={code} onChange={event=>setCode(event.target.value)} className="mt-2 w-full rounded-2xl border border-black/10 px-4 py-3" /></label>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<button className="mt-5 w-full rounded-full bg-[#245b46] py-3 font-bold text-white">进入后台</button></form></main>;
  return <main className="page-shell py-10"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">用户反馈</h1><p className="mt-1 text-sm text-[#65706a]">只展示产品反馈，不展示访客身份。</p></div><button onClick={async()=>{await fetch("/api/admin/auth",{method:"DELETE"});setLoggedIn(false);}} className="rounded-full border px-4 py-2 text-sm font-bold">退出</button></div>
    <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["全部",data?.stats.total],["很有帮助",data?.stats.helpful],["基本可用",data?.stats.usable],["不太有用",data?.stats.notHelpful]].map(([label,value])=><div key={label} className="card rounded-2xl p-4"><p className="text-xs text-[#707a74]">{label}</p><strong className="mt-1 block text-2xl">{value??"—"}</strong></div>)}</div>
    <form className="mt-5 flex flex-wrap gap-2 rounded-2xl bg-white p-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setQuery(new URLSearchParams(form as never).toString());}}><select name="kind" className="rounded-xl border px-3 py-2"><option value="all">全部类型</option><option value="overall">总体反馈</option><option value="day">单日反馈</option></select><select name="rating" className="rounded-xl border px-3 py-2"><option value="">全部评分</option><option value="helpful">很有帮助</option><option value="usable">基本可用</option><option value="not_helpful">不太有用</option></select><input name="destination" placeholder="目的地" className="rounded-xl border px-3 py-2"/><input name="from" type="date" className="rounded-xl border px-3 py-2"/><input name="to" type="date" className="rounded-xl border px-3 py-2"/><button className="rounded-xl bg-[#245b46] px-4 py-2 font-bold text-white">筛选</button><a href={`/api/admin/feedback?${query}&format=csv`} className="rounded-xl border px-4 py-2 font-bold">导出 CSV</a></form>
    {error&&<p className="mt-4 text-red-700">{error}</p>}<div className="mt-5 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#eef3ef]"><tr>{["时间","类型","目的地","第几天","评分","问题","备注","攻略"].map(item=><th key={item} className="p-3">{item}</th>)}</tr></thead><tbody>{data?.rows.map(row=><tr key={row.id} className="border-t border-black/5"><td className="p-3 whitespace-nowrap">{new Date(row.createdAt).toLocaleString("zh-CN")}</td><td className="p-3">{row.kind==="day"?"单日":"总体"}</td><td className="p-3">{row.destination}</td><td className="p-3">{row.dayNumber??"—"}</td><td className="p-3">{ratingLabel[row.rating]||"其他"}</td><td className="p-3">{row.tags.join("、")||"—"}</td><td className="max-w-64 p-3">{row.comment||"—"}</td><td className="p-3"><a href={`/trip/${row.tripId}`} target="_blank" className="font-bold text-[#245b46]">查看</a></td></tr>)}</tbody></table></div>
    {data&&<div className="mt-4 flex justify-center gap-3"><button disabled={data.page<=1} onClick={()=>setQuery(query.replace(/page=\d+/,`page=${data.page-1}`))} className="rounded-full border px-4 py-2 disabled:opacity-30">上一页</button><span className="py-2">{data.page}/{data.pages}</span><button disabled={data.page>=data.pages} onClick={()=>setQuery(query.replace(/page=\d+/,`page=${data.page+1}`))} className="rounded-full border px-4 py-2 disabled:opacity-30">下一页</button></div>}
  </main>;
}
