"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { trackEvent } from "@/features/analytics/client";

type UserPreview={maskedEmail:string;balance:number};
type History={createdAt:string;email:string;amount:number;balanceAfter:number;ledgerId:string;metadata:Record<string,unknown>};
export function PointsAdmin({authorized}:{authorized:boolean}){
  const [email,setEmail]=useState("");const [points,setPoints]=useState(1);const [reason,setReason]=useState("");const [note,setNote]=useState("");const [preview,setPreview]=useState<UserPreview|null>(null);const [history,setHistory]=useState<History[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [key,setKey]=useState(crypto.randomUUID());
  useEffect(()=>{if(authorized)void loadHistory();},[authorized]);
  async function loadHistory(){const response=await fetch("/api/admin/points/grant");if(response.ok)setHistory(((await response.json()) as {history:History[]}).history);}
  async function lookup(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");setPreview(null);trackEvent("admin_point_grant_started",{pageName:"admin"});try{const response=await fetch(`/api/admin/points/grant?email=${encodeURIComponent(email.trim().toLowerCase())}`);const payload=await response.json() as {user?:UserPreview;error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message||"查询失败");setPreview(payload.user!);}catch(error){setMessage(error instanceof Error?error.message:"查询失败");}finally{setBusy(false);}}
  async function grant(){if(!preview)return;setBusy(true);setMessage("");try{const response=await fetch("/api/admin/points/grant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:email.trim().toLowerCase(),points,reason,note,idempotencyKey:key})});const payload=await response.json() as {balance?:number;reused?:boolean;notification?:string;error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message||"发放失败");setMessage(`${payload.reused?"该操作已处理，":"发放成功，"}当前余额 ${payload.balance} 点${payload.notification==="failed"?"；通知邮件发送失败，但点数已到账":""}`);setPreview(null);setReason("");setNote("");setKey(crypto.randomUUID());trackEvent("admin_point_grant_succeeded",{pageName:"admin",metadata:{points}});await loadHistory();}catch(error){setMessage(error instanceof Error?error.message:"发放失败");trackEvent("admin_point_grant_failed",{pageName:"admin"});}finally{setBusy(false);}}
  if(!authorized)return <main className="page-shell py-20"><p>请先从数据后台登录。</p><Link href="/admin/analytics" className="mt-4 inline-block underline">返回管理员登录</Link></main>;
  return <main className="page-shell py-10"><nav className="flex flex-wrap gap-3 text-sm font-bold"><Link href="/admin/analytics" className="rounded-full border px-4 py-2">数据概览</Link><Link href="/admin/points" className="rounded-full bg-[#245b46] px-4 py-2 text-white">发放点数</Link><Link href="/admin/feedback" className="rounded-full border px-4 py-2">用户反馈</Link></nav><div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,420px)_1fr]"><section className="card rounded-3xl p-6"><h1 className="text-2xl font-bold">按注册邮箱发放点数</h1><form onSubmit={lookup} className="mt-5 space-y-4"><label className="block text-sm font-bold">用户邮箱<input type="email" required value={email} onChange={event=>{setEmail(event.target.value);setPreview(null);}} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">发放点数<input type="number" min={1} max={100} required value={points} onChange={event=>setPoints(Number(event.target.value))} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">发放原因<input minLength={4} maxLength={100} required value={reason} onChange={event=>setReason(event.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">备注（选填）<textarea maxLength={200} value={note} onChange={event=>setNote(event.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><button disabled={busy} className="w-full rounded-full bg-[#245b46] p-3 font-bold text-white disabled:opacity-50">查找并确认</button></form>{preview&&<div className="mt-5 rounded-2xl bg-[#eef3ec] p-4 text-sm"><p>用户：<strong>{preview.maskedEmail}</strong></p><p className="mt-1">当前 {preview.balance} 点，本次增加 {points} 点，发放后 {preview.balance+points} 点</p><button type="button" disabled={busy} onClick={grant} className="mt-4 w-full rounded-full bg-[#245b46] p-3 font-bold text-white">二次确认发放</button></div>}{message&&<p role="status" className="mt-4 rounded-xl bg-[#fff2d9] p-3 text-sm">{message}</p>}</section><section className="card overflow-x-auto rounded-3xl p-6"><h2 className="text-xl font-bold">操作历史</h2><table className="mt-4 min-w-[720px] w-full text-sm"><thead><tr className="text-left"><th>时间</th><th>用户</th><th>点数</th><th>原因</th><th>余额</th><th>通知</th><th>账本ID</th></tr></thead><tbody>{history.map(row=><tr key={row.ledgerId} className="border-t"><td className="py-3">{new Date(row.createdAt).toLocaleString("zh-CN")}</td><td>{row.email}</td><td>+{row.amount}</td><td>{String(row.metadata.reason||"—")}</td><td>{row.balanceAfter}</td><td>{{sent:"已发送",failed:"失败",skipped:"未配置",pending:"处理中"}[String(row.metadata.notificationStatus)]||"—"}</td><td className="font-mono text-xs">{row.ledgerId.slice(0,8)}…</td></tr>)}</tbody></table></section></div></main>;
}
