"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
type Preview={userId:string;maskedEmail:string;mode:"normal"|"tester_unlimited";todayGenerationRequests:number;totalTrips:number;failedTasks:number;balance:number;registeredAt:string;lastUsedAt:string|null;updatedAt:string|null};
export function TestUsersAdmin({authorized}:{authorized:boolean}){
  const[email,setEmail]=useState(""),[reason,setReason]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function lookup(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");setPreview(null);try{const response=await fetch(`/api/admin/users/generation-access?email=${encodeURIComponent(email.trim().toLowerCase())}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"查询失败");setPreview(payload.user);}catch(error){setMessage(error instanceof Error?error.message:"查询失败");}finally{setBusy(false)}}
  async function update(mode:"normal"|"tester_unlimited"){if(!preview||!confirm(mode==="tester_unlimited"?"确认设为测试用户？":"确认恢复普通限制？"))return;setBusy(true);setMessage("");try{const response=await fetch("/api/admin/users/generation-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:email.trim().toLowerCase(),mode,reason})});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||"更新失败");setMessage(mode==="tester_unlimited"?"测试权限已开启":"已恢复普通限制");setPreview(value=>value?{...value,mode,updatedAt:new Date().toISOString()}:value);}catch(error){setMessage(error instanceof Error?error.message:"更新失败");}finally{setBusy(false)}}
  if(!authorized)return <main className="page-shell py-20"><p>请先从数据后台登录。</p><Link href="/admin/analytics" className="mt-4 inline-block underline">返回管理员登录</Link></main>;
  return <main className="page-shell py-10"><nav className="flex flex-wrap gap-3 text-sm font-bold"><Link href="/admin/analytics" className="rounded-full border px-4 py-2">数据概览</Link><Link href="/admin/points" className="rounded-full border px-4 py-2">发放点数</Link><Link href="/admin/test-users" className="rounded-full bg-[#245b46] px-4 py-2 text-white">测试用户</Link><Link href="/admin/feedback" className="rounded-full border px-4 py-2">用户反馈</Link></nav><section className="card mt-8 max-w-2xl rounded-3xl p-6"><h1 className="text-2xl font-bold">测试用户管理</h1><p className="mt-2 text-sm text-[#65706a]">只豁免攻略生成和修改的每日次数；海报点数、并发、短时防刷和全站熔断仍然生效。</p><form onSubmit={lookup} className="mt-5 space-y-4"><label className="block text-sm font-bold">已注册用户邮箱<input type="email" required value={email} onChange={event=>{setEmail(event.target.value);setPreview(null)}} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">操作原因<input required minLength={4} maxLength={100} value={reason} onChange={event=>setReason(event.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><button disabled={busy} className="w-full rounded-full bg-[#245b46] p-3 font-bold text-white disabled:opacity-50">查找用户</button></form>{preview&&<div className="mt-5 rounded-2xl bg-[#eef3ec] p-4 text-sm"><p>用户：<strong>{preview.maskedEmail}</strong></p><p className="mt-1 break-all">用户 ID：{preview.userId}</p><p className="mt-1">当前权限：<strong>{preview.mode==="tester_unlimited"?"测试权限":"普通限制"}</strong></p><p className="mt-1">攻略：{preview.totalTrips} · 失败任务：{preview.failedTasks} · 点数：{preview.balance}</p><p className="mt-1">今日生成/修改请求：{preview.todayGenerationRequests}</p><p className="mt-1">注册：{new Date(preview.registeredAt).toLocaleString("zh-CN")}</p><p className="mt-1">最近使用：{preview.lastUsedAt?new Date(preview.lastUsedAt).toLocaleString("zh-CN"):"暂无"}</p><p className="mt-1">权限更新：{preview.updatedAt?new Date(preview.updatedAt).toLocaleString("zh-CN"):"尚未调整"}</p><button type="button" disabled={busy} onClick={()=>void update(preview.mode==="normal"?"tester_unlimited":"normal")} className="mt-4 w-full rounded-full bg-[#245b46] p-3 font-bold text-white disabled:opacity-50">{preview.mode==="normal"?"设为测试用户":"恢复普通限制"}</button></div>}{message&&<p role="status" className="mt-4 rounded-xl bg-[#fff2d9] p-3 text-sm">{message}</p>}</section></main>;
}
