import Taro from "@tarojs/taro";
const ACCESS="yjchufa-mini-access",REFRESH="yjchufa-mini-refresh";
export type MiniappErrorAction="retry"|"login"|"back"|"support"|"none";
export class MiniappRequestError extends Error{constructor(message:string,public code:string,public requestId:string|null,public action:MiniappErrorAction){super(message)}}
const actionFor=(code:string,status:number):MiniappErrorAction=>status===401?"login":code.includes("NOT_FOUND")||code.includes("EXPIRED")?"back":status===429||status>=500?"retry":"none";
function parseError(data:unknown,status:number){const value=data as {error?:{message?:string;code?:string;requestId?:string}};const code=value?.error?.code||"NETWORK_ERROR";return new MiniappRequestError(value?.error?.message||"网络开小差了，请稍后重试",code,value?.error?.requestId||null,actionFor(code,status));}
export const getAccessToken=()=>Taro.getStorageSync<string>(ACCESS)||"";
const getRefreshToken=()=>Taro.getStorageSync<string>(REFRESH)||"";
export function saveSession(value:{sessionToken:string;refreshToken:string}){Taro.setStorageSync(ACCESS,value.sessionToken);Taro.setStorageSync(REFRESH,value.refreshToken)}
export function clearSession(){Taro.removeStorageSync(ACCESS);Taro.removeStorageSync(REFRESH)}
export async function ensureWechatLogin(){const login=await Taro.login();const result=await requestPublic<{sessionToken:string;refreshToken:string}>("/api/miniapp/auth/login",{method:"POST",data:{code:login.code,requestId:cryptoId()}});saveSession(result);return result}
export const cryptoId=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const origin=process.env.TARO_APP_API_ORIGIN||"https://www.yjchufa.com";
export async function requestPublic<T>(path:string,options:Partial<Taro.request.Option>={}){try{const response=await Taro.request({...options,url:`${origin}${path}`,timeout:20_000,header:{"content-type":"application/json",...options.header}});if(response.statusCode>=400)throw parseError(response.data,response.statusCode);return response.data as T}catch(error){if(error instanceof MiniappRequestError)throw error;throw new MiniappRequestError("网络不可用，请检查连接后重试","NETWORK_UNAVAILABLE",null,"retry")}}
async function renew(){const refreshToken=getRefreshToken();if(refreshToken){try{const value=await requestPublic<{sessionToken:string;refreshToken:string}>("/api/miniapp/auth/refresh",{method:"POST",data:{refreshToken}});saveSession(value);return}catch{clearSession()}}await ensureWechatLogin()}
export async function request<T>(path:string,options:Partial<Taro.request.Option>={},retried=false){let token=getAccessToken();if(!token){await ensureWechatLogin();token=getAccessToken()}try{const response=await Taro.request({...options,url:`${origin}${path}`,timeout:20_000,header:{"content-type":"application/json",authorization:`Bearer ${token}`,...options.header}});if(response.statusCode===401&&!retried){await renew();return request<T>(path,options,true)}if(response.statusCode===401){clearSession();throw new MiniappRequestError("登录状态已过期，请重新进入","MINIAPP_SESSION_EXPIRED",null,"login")};if(response.statusCode>=400)throw parseError(response.data,response.statusCode);return response.data as T}catch(error){if(error instanceof MiniappRequestError)throw error;throw new MiniappRequestError("网络不可用，请检查连接后重试","NETWORK_UNAVAILABLE",null,"retry")}}
export async function logout(){try{await request("/api/miniapp/auth/logout",{method:"POST",data:{}})}finally{clearSession()}}
