import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import sharp from "sharp";
import {planPosterLayout,validatePosterCompleteness,type LayoutDay} from "../src/server/posters/layout";
import {timelinePosterV2SpecSchema} from "../src/schemas/trip-image";
import {renderPosterPages} from "../src/server/posters/render";

async function main(){const pixel=await sharp({create:{width:420,height:280,channels:3,background:"#9fc5aa"}}).webp().toBuffer(),dataUrl=`data:image/webp;base64,${pixel.toString("base64")}`;const source=(dayNumber:number,count:number):LayoutDay=>({dayNumber,date:null,title:`第${dayNumber}天完整路线`,city:"苏州",tips:["核实开放时间"],activities:Array.from({length:count},(_,index)=>({id:`day-${dayNumber}-activity-${index+1}`,time:`${String(8+index).padStart(2,"0")}:00–${String(9+index).padStart(2,"0")}:00`,name:`活动地点${index+1}`,note:"完整保留活动说明，不允许被截断。"}))});const days=[source(1,8),source(2,4)],layout=planPosterLayout(days);assert.equal(layout.pageCount,2);assert.equal(validatePosterCompleteness(layout).valid,true);const pages=layout.pages.map(page=>({pageNumber:page.pageNumber,layoutMode:page.layoutMode,dayRange:`DAY ${page.days[0]!.dayNumber}`,days:page.days.map(day=>({...day,activities:day.activities.map(activity=>({sourceActivityId:activity.id,time:activity.time,name:activity.name,note:activity.note,category:"attraction" as const,visualAsset:{id:randomUUID(),cacheKey:"a".repeat(40),dataUrl,category:"attraction" as const,altText:"测试视觉",reused:false}}))})),tips:["景点图片为 AI 视觉示意，请以实际现场为准。"]}));const spec=timelinePosterV2SpecSchema.parse({kind:"travel_poster",version:"oneclick_travel_dynamic_layout_v12",tripId:randomUUID(),tripVersion:1,aspectRatio:"3:4",width:1024,height:1536,title:"苏州2日完整行程",subtitle:"动态分页测试",destination:"苏州",daysCount:2,pages,layoutAudit:{layoutPlanHash:layout.layoutPlanHash,expectedActivityIds:layout.expectedActivityIds,renderedActivityIds:layout.renderedActivityIds,estimatedHeights:layout.estimatedHeights},model:"test",quality:"low",estimatedCostUsd:0});const rendered=await renderPosterPages(spec);assert.equal(rendered.length,2);for(const image of rendered){const metadata=await sharp(image).metadata();assert.equal(metadata.width,1024);assert.equal(metadata.height,1536);}console.log("poster dynamic render passed: 12/12 activities, 2 pages");}
main().catch(error=>{console.error(error);process.exitCode=1});
