import { and, desc, eq, or } from "drizzle-orm";
import { createHash } from "node:crypto";
import { z } from "zod";
import { hasAdminAccess } from "@/server/auth/admin";
import { grantPoints } from "@/server/commerce/points";
import { getDatabase } from "@/server/database/client";
import { pointAccounts, pointLedger, users } from "@/server/database/schema";
import { apiError, assertTrustedMutation, HttpError, readJsonBody } from "@/server/http";

const attempts = new Map<string, number[]>();
const maxGrant = Math.min(1000, Math.max(1, Number(process.env.ADMIN_POINT_GRANT_MAX || 100)));
const schema = z.object({ email:z.string().trim().email().max(254).transform(value=>value.toLowerCase()), points:z.number().int().min(1).max(maxGrant), reason:z.string().trim().min(4).max(100), note:z.string().trim().max(200).optional().default(""), idempotencyKey:z.string().uuid() });
function masked(email:string){const [name,domain]=email.split("@");return `${name.slice(0,2)}***@${domain}`;}
function limit(request:Request){const riskSource=(request.headers.get("x-forwarded-for")||"admin").split(",")[0]!.trim();const key=createHash("sha256").update(`admin-grant:${riskSource}`).digest("hex").slice(0,24);const now=Date.now();const recent=(attempts.get(key)||[]).filter(value=>now-value<10*60_000);if(recent.length>=10)throw new HttpError(429,"操作过于频繁，请稍后再试","RATE_LIMITED");recent.push(now);attempts.set(key,recent);}
async function requireAdmin(){if(!await hasAdminAccess())throw new HttpError(401,"未授权","ADMIN_REQUIRED");}

export async function GET(request:Request){try{await requireAdmin();const db=getDatabase();const url=new URL(request.url);const email=url.searchParams.get("email")?.trim().toLowerCase();if(email){const [user]=await db.select({id:users.id,email:users.email,verifiedAt:users.verifiedAt,balance:pointAccounts.availablePoints}).from(users).leftJoin(pointAccounts,eq(pointAccounts.userId,users.id)).where(and(eq(users.email,email),eq(users.status,"active"))).limit(1);if(!user||!user.verifiedAt)throw new HttpError(404,"该邮箱尚未注册","USER_NOT_FOUND");return Response.json({user:{maskedEmail:masked(user.email),balance:user.balance??0}});}const rows=await db.select({createdAt:pointLedger.createdAt,email:users.email,amount:pointLedger.amount,balanceAfter:pointLedger.balanceAfter,ledgerId:pointLedger.id,metadata:pointLedger.metadata}).from(pointLedger).innerJoin(users,eq(users.id,pointLedger.userId)).where(or(eq(pointLedger.type,"admin_grant"),eq(pointLedger.type,"grant"))).orderBy(desc(pointLedger.createdAt)).limit(100);return Response.json({history:rows.filter(row=>row.metadata.source==="admin_grant").map(row=>({...row,email:masked(row.email)}))});}catch(error){return apiError(error);}}

export async function POST(request:Request){try{assertTrustedMutation(request);await requireAdmin();limit(request);const parsed=schema.safeParse(await readJsonBody(request));if(!parsed.success)throw new HttpError(400,"参数无效","INVALID_GRANT");const db=getDatabase();const [user]=await db.select({id:users.id,email:users.email,verifiedAt:users.verifiedAt}).from(users).where(and(eq(users.email,parsed.data.email),eq(users.status,"active"))).limit(1);if(!user||!user.verifiedAt)throw new HttpError(404,"该邮箱尚未注册","USER_NOT_FOUND");const result=await grantPoints({userId:user.id,points:parsed.data.points,businessKey:`admin:${parsed.data.idempotencyKey}`,source:"admin_grant",reason:parsed.data.reason,note:parsed.data.note,administrator:"access_code_admin"});let notification:"sent"|"failed"|"skipped"="skipped";if(!result.reused){notification=await sendNotification(user.email,parsed.data.points,result.balance,parsed.data.reason);await db.update(pointLedger).set({metadata:{source:"admin_grant",reason:parsed.data.reason,note:parsed.data.note,administrator:"access_code_admin",notificationStatus:notification}}).where(eq(pointLedger.id,result.ledgerId));}return Response.json({ok:true,...result,maskedEmail:masked(user.email),notification});}catch(error){return apiError(error);}}

async function sendNotification(email:string,points:number,balance:number,reason:string):Promise<"sent"|"failed"|"skipped">{if(!process.env.RESEND_API_KEY||!process.env.AUTH_EMAIL_FROM)return "skipped";try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:process.env.AUTH_EMAIL_FROM,to:[email],subject:"一键出发点数已到账",html:`<p>本次到账 <strong>${points} 点</strong>，当前余额 ${balance} 点。</p><p>发放原因：${escapeHtml(reason)}</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL || "https://www.yjchufa.com"}/account">查看账户</a></p>`})});return response.ok?"sent":"failed";}catch{return "failed";}}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));}
